### PR TITLE
Dockerfile improvements 

### PR DESCRIPTION
**Pull request by agomezl**
* Now when building a new container it looks for an available `cakeml-token` in the build context
* `wget` added as a dependency

### CODE REVIEW

**Comment by xrchz** [comment]
Perhaps this can wait till `wget` is removed from the dependencies?

**Comment by agomezl** [comment]
Sure! I already have a working container at [agomezl/oven](https://hub.docker.com/r/agomezl/oven/) but I try to keep the `Dockerfile` update in this repo if someone want to reproduce the build

**Comment by ncough** [comment]
The dependency on `wget` will be removed by https://github.com/CakeML/cakeml/pull/489

**Comment by xrchz** [comment]
Is this still wanted?

**Comment by agomezl** [comment]
It would still be nice to have, however, I abandoned the idea of using containers in `oven` since they kept mysteriously running out of resources

**Comment by xrchz** [comment]
I actually prefer to remove the Dockerfile at this point, because we're not supporting or using it.

**Comment by agomezl** [comment]
That is true, however I'm currently trying to create a mock regression server (via #16) in order to fix what is wrong with the docker workers

**Pull request closed without merging**
