### PR TITLE
Add early artefact upload

### PR DESCRIPTION
**Pull request by ncough**
This change adds the option to upload build results
before the entire regression task has completed. The
build-sequence entry must be annotated with a list of
artefacts, separated by ':'.

### CODE REVIEW

**Comment by ncough** [comment]
This change is required to allow for the early results from `sexpr` bootstrap, which won't fail due to memory constraints like the full bootstrap. I haven't been able to test this on a server setup, so I am not 100% certain its valid.

**Comment by xrchz** [comment]
OK, this seems reasonable. Do you want to also make the default end-of-regression artefacts work like this? i.e., we annotate the last few dirs with their uploads. That would be nice, I think.

**Comment by xrchz** [comment]
(happy to merge this first if you want)

**Comment by ncough** [comment]
I agree, the end-of-regression artefacts can go through this process as well, as the 64-bit result should be available a little sooner this way. I'll put together the change to the build-sequence once this has been merged.

**Comment by xrchz** [comment]
Do we still need the final `upload_artefacts` call now? Won't they have been uploaded early already?

**Pull request merged**
