### PR TITLE
Workers track status and can restart tasks.

### PR DESCRIPTION
**Pull request by talsewell**
The worker programs will now record what they're doing for any
given job in status/job_(id)

If a task finishes, and the last line in status/job_(id) is
'Restart' then the worker will reattempt the task. This allows
an admin to restart a task that has encountered a transient
deadlock.

### CODE REVIEW

**Comment by xrchz** [comment]
Nice work. I think the job formatter on the server will need a slight tweak to handle the "Restarting task." lines. Can you add?

**Comment by talsewell** [comment]
Hmm, I don't really see what's the problem here. It looks like the formatting of the log is done by the client before pushing lines with Append.

**Comment by xrchz** [comment]
I think check `process` in `serverLib.sml`

**Comment by talsewell** [comment]
OK. I've had a look. Not my favourite design, I'll say that.

But, it ought to just work. The format_log_line function looks for lines with " Finished" and formats them, and falls back to a default case for all the other line types ("Starting ...", "Claimed job" etc). New default cases should just work, as long as they don't contain the string "Finished " anywhere.

**Comment by xrchz** [comment]
OK let's see how it goes

**Pull request merged**
